# Generated by Django 2.2.6 on 2020-06-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBVTest', '0003_auto_20200616_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
    ]
