# Generated by Django 2.2.6 on 2020-06-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBVTest', '0005_auto_20200616_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='车名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('brand', models.CharField(max_length=16, verbose_name='品牌')),
            ],
            options={
                'verbose_name': '汽车表',
                'verbose_name_plural': '汽车表',
                'db_table': 'Car',
            },
        ),
    ]
